"""app/styles — design token helpers for PySide6.

Generated artefacts (tokens.qss, tokens.py) are produced by
``tools/build_qss.py`` / ``make tokens`` and are .gitignore'd.
This module provides a stable import surface that survives the
generated files not yet existing (e.g. fresh checkout before
``make tokens``).
"""

from __future__ import annotations

from pathlib import Path

# tokens.py is a generated file (tools/build_qss.py parses
# ../llm-swarm-webclient/frontend/src/styles/tokens.css and emits
# app/styles/tokens.py).  On a fresh checkout it does not exist yet.
# We do a deferred availability-check so that any caller of
# `from app.styles import ...` gets a clear, actionable error instead
# of a cryptic AttributeError or silent wrong-colour rendering.
_TOKENS_PY = Path(__file__).resolve().parent / "tokens.py"
if not _TOKENS_PY.exists():
    raise ImportError(
        "app/styles/tokens.py has not been generated yet.\n"
        "Run `make tokens` to generate it from the webclient design tokens.\n"
        "Source of truth: ../llm-swarm-webclient/frontend/src/styles/tokens.css\n"
        "Quick fix: make install  (runs uv sync + make tokens)"
    )

_STYLES_DIR = Path(__file__).resolve().parent


def load_qss() -> str:
    """Return the contents of the generated tokens.qss stylesheet.

    Raises ``FileNotFoundError`` with a helpful message if the file has not
    been generated yet (run ``make tokens``).
    """
    qss_path = _STYLES_DIR / "tokens.qss"
    if not qss_path.exists():
        raise FileNotFoundError(
            f"tokens.qss not found at {qss_path}. "
            "Run `make tokens` to generate it from the webclient design tokens."
        )
    return qss_path.read_text(encoding="utf-8")


def load_pairing_qss() -> str:
    """Return the contents of the pairing-specific stylesheet.

    Unlike ``tokens.qss``, ``pairing.qss`` is a hand-authored file that
    lives alongside the generated tokens.  It is appended to ``tokens.qss``
    by ``apply_to_app()``.

    Returns an empty string if the file does not exist (graceful degradation).
    """
    pairing_qss_path = _STYLES_DIR / "pairing.qss"
    if not pairing_qss_path.exists():
        return ""
    return pairing_qss_path.read_text(encoding="utf-8")


def apply_to_app(app: object) -> None:
    """Load and apply tokens.qss + pairing.qss to a QApplication instance.

    Usage::

        from PySide6.QtWidgets import QApplication
        from app.styles import apply_to_app

        qt_app = QApplication(sys.argv)
        apply_to_app(qt_app)

    Also registers bundled fonts (Inter, JetBrains Mono) via Qt resource
    system if ``resources_rc`` is available.
    """
    # Register fonts from Qt resource bundle (generated by pyside6-rcc)
    try:
        from PySide6.QtGui import QFontDatabase

        from app.resources import resources_rc as _  # noqa: F401

        for font_path in [
            ":/fonts/Inter-Variable.ttf",
            ":/fonts/JetBrainsMono-Regular.ttf",
            ":/fonts/JetBrainsMono-Medium.ttf",
        ]:
            QFontDatabase.addApplicationFont(font_path)
    except ImportError:
        # resources_rc not yet generated — fonts fall back to system fonts
        pass

    # Apply stylesheet: base tokens + pairing extensions
    stylesheet = load_qss() + "\n" + load_pairing_qss()
    # app is QApplication but we avoid the import at module level to keep
    # this module importable in non-Qt contexts (tests, build scripts)
    app.setStyleSheet(stylesheet)  # type: ignore[union-attr]
