"""app/resources — Qt resource bundle.

resources_rc.py is auto-generated by ``pyside6-rcc`` (see ``make tokens``).
It is .gitignore'd and must be regenerated after checkout.
"""

from __future__ import annotations
